# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.cache/wt [current_project]
set_property parent.project_path C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.srcs/sources_1/new/RAM_Module.v
  C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.srcs/sources_1/new/AXI_Slave_RAM.v
}
read_xdc C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.srcs/constrs_1/new/AXI_Slave_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/vamsi/Desktop/AXI_Slave_Interface/AXI_RAM_SLAVE/AXI_RAM_SLAVE.srcs/constrs_1/new/AXI_Slave_Constraints.xdc]

synth_design -top AXI_Slave_RAM -part xc7a100tcsg324-1 -flatten_hierarchy none
write_checkpoint -noxdef AXI_Slave_RAM.dcp
catch { report_utilization -file AXI_Slave_RAM_utilization_synth.rpt -pb AXI_Slave_RAM_utilization_synth.pb }
